In [2]:
import tskit
import msprime
import pyslim 
import demesdraw 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tszip
from tqdm.auto import tqdm

from utils import *
from relate_utils import *

In [9]:
mts = tszip.decompress('lovely_trees_subsampled_full_arg.tsz')

In [10]:
df = recombination_summary(mts)

In [15]:
mts

In [11]:
df

,rec_number,child,descendant_samples,descendant_nodes,breakpoint,time,tree_index_left,tree_index_right,coal_left,coal_right
0,1,14,[14],[],499595.0,2.091968,18,19,21.0,23.0
1,2,21,[21],[],500156.0,16.782350,137,138,13.0,21.0
2,3,241,[86],"[86, 158, 165, 186]",499879.0,23.512299,73,74,16.0,15.0
3,4,69,[69],[],500244.0,28.865046,156,157,8.0,5.0
4,5,95,[95],[],499724.0,29.260023,43,44,14.0,25.0
...,...,...,...,...,...,...,...,...,...,...
244,245,1332,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",500052.0,103220.257407,113,114,NaN,NaN
245,246,1329,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",500440.0,105251.086729,210,211,NaN,NaN
246,247,1323,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",499971.0,105266.040594,91,92,NaN,NaN
247,248,1295,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",499710.0,107646.218254,37,38,NaN,NaN
248,249,1330,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",499907.0,107780.989279,80,81,NaN,NaN

In [26]:
targets = {29,75,91}                                                                                                                                                     
df[df['descendant_samples'].apply(lambda x: targets.issubset(x))]

,rec_number,child,descendant_samples,descendant_nodes,breakpoint,time,tree_index_left,tree_index_right,coal_left,coal_right
72,73,848,"[0, 8, 16, 23, 29, 35, 53, 56, 61, 67, 71, 73,...","[0, 8, 16, 23, 29, 35, 53, 56, 61, 67, 71, 73,...",500490.0,3598.164263,218,219,2.0,3.0
73,74,860,"[0, 23, 29, 35, 53, 56, 66, 67, 73, 75, 86, 88...","[0, 23, 29, 35, 53, 56, 66, 67, 73, 75, 86, 88...",500340.0,3631.319974,183,184,-1.0,5.0
74,75,864,"[0, 8, 16, 23, 29, 35, 53, 56, 61, 66, 67, 71,...","[0, 8, 16, 23, 29, 35, 53, 56, 61, 66, 67, 71,...",500445.0,3761.923039,212,213,1.0,1.0
79,80,865,"[0, 23, 29, 35, 53, 56, 66, 67, 73, 75, 86, 88...","[0, 23, 29, 35, 53, 56, 66, 67, 73, 75, 86, 88...",500397.0,4037.096702,196,197,3.0,1.0
82,83,872,"[3, 5, 11, 13, 20, 21, 22, 23, 29, 33, 34, 36,...","[3, 5, 11, 13, 20, 21, 22, 23, 29, 33, 34, 36,...",500019.0,4310.878245,103,104,7.0,6.0
...,...,...,...,...,...,...,...,...,...,...
244,245,1332,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",500052.0,103220.257407,113,114,NaN,NaN
245,246,1329,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",500440.0,105251.086729,210,211,NaN,NaN
246,247,1323,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",499971.0,105266.040594,91,92,NaN,NaN
247,248,1295,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",499710.0,107646.218254,37,38,NaN,NaN
248,249,1330,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...","[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",499907.0,107780.989279,80,81,NaN,NaN

In [13]:
for m in mts.mutations():
    if mts.site(m.site).position == 900109:
        print(m.node)

807

In [14]:
t = mts.at(900109)
print([s for s in t.samples(807)])

[69, 68, 53, 4, 82]